### PR TITLE
Fixed bug City name space-separated is not space separated #103

### LINKED ISSUE #103: City name space-separated is not space separated
#### Description

https://travis-ci.org/JaroslawWiosna/regionalizer/builds/298694237?utm_source=github_status&utm_medium=notification 
1348-1350 lines:
```
regionalizeUsingRandom
The best capitals would be GrodziskMazowiecki Sycow 
Happiness level = 155807595
```

`GrodziskMazowiecki` should be separated just like in database:
`Grodzisk Mazowiecki|13.19|30593|52.1|20.6167`

--- 

#### Release affected

`v0.3.1`

---

#### Priority

low

---

#### Is there possible contributor who could fix the issue

@kermit10000000 

---

### PR DESCRIPTION
**Pull request by kermit10000000**
Added distinction between cities names given in output with comma. Otherwise cities with double names were seen as two separate cities.
Closes #103

Signed-off-by: Wojciech Mielczarek <kermit10000000@gmail.com>

### CODE REVIEW

**Comment by kermit10000000** [comment]
obraz

**Comment by kermit10000000** [comment]
-0,01% 😄 and coveral is not entering place that the real code is(tested). that means coverals has some bugs or something.

**Comment by kermit10000000** [comment]
new commit adds: clang format was being run

**Comment by kermit10000000** [comment]
Backlog 9; Description of getTheClosestCityThatIsBiggerThanMe needs to be changed. It is out-dated

File: ClosestCity/ClosestCity.cpp [hunk 1]
```diff
@@ -36,7 +36,7 @@ std::string getTheClosestCityThatIsBiggerThanMe(std::vector<City> vec,
             });
 
         auto distanceToTheClosestCity = 100000;
```
Comment (JaroslawWiosna) [inline ClosestCity/ClosestCity.cpp]: Let's change this number.
afak, we have to initialize `distanceToTheClosestCity` with some **big** number.
That's cool.
let's use numeric limits instead:
https://ideone.com/3sU7Qf
`auto distanceToTheClosestCity = std::numeric_limits<std::size_t>::max();`
With this everybody knows that the variable is the greatest number there is.

File: Region/Region.cpp [hunk 2]
```diff
@@ -237,7 +237,11 @@ Region::regionalizeUsingRandom(unsigned numberOfRegions) {
     delete bar;
     std::cout << "The best capitals would be ";
     for (auto i : bestCapitalsSoFar) {
-        std::cout << i << " ";
+        if (i == bestCapitalsSoFar[bestCapitalsSoFar.size() - 1]) {
```
Comment (JaroslawWiosna) [inline Region/Region.cpp:240]: Good :)

File: tests/ClosestCity/ClosestCity.cpp [hunk 3]
```diff
@@ -15,119 +15,189 @@
...
+    // TODO:vector pobierany z pliku moc 10 cities databaseReaderem.
     std::string path = "../../../database/Poland-Cities010-Top10-mock.txt";
-    std::vector <City> vec = DatabaseReader::readCitiesFromFile(path);
-    
-    std::string CityNames[]={"Warsaw","Lodz","Szczecin", "Katowice", "Poznan","Krakow"};
-    ClosestCity::removeCitiesInVectorThatAreSmallerThanMe(vec,CityNames[0]);
-    ASSERT_EQ(1, vec.size()) << "We should erase cities smaller than Warsaw and therefore have just one city in vector but we have: " << vec.size() << " of them";
-    ASSERT_TRUE(findCity(vec,CityNames[0])) << "We should have one " << CityNames[0] << " but we found" << findCity(vec,CityNames[0]);
-    ASSERT_FALSE(findCity(vec,CityNames[1])) << "We should have none " << CityNames[1] << " but it is still in the vector so the function removeCitiesInVectorThatAreSmallerThanMe is working wrong";
+    std::vector<City> vec = DatabaseReader::readCitiesFromFile(path);
```
Comment (JaroslawWiosna) [inline tests/ClosestCity/ClosestCity.cpp]: `DatabaseReader::readCitiesFromFile(path);` returns `std::vector<City>` so why do we need to write is explicitly?
That's just an open question. Perhaps it is fine to write `std::vector<City>` insted of auto.

File: tests/ClosestCity/ClosestCity.cpp [hunk 4]
```diff
@@ -15,119 +15,189 @@
...
+
     // testing with flags and messages
     vec.clear();
     vec = DatabaseReader::readCitiesFromFile(path);
-    
-    std::string NextCity = ClosestCity::getTheClosestCityThatIsBiggerThanMe(vec,CityNames[0]);
 
-   ASSERT_EQ("", NextCity) << "As Warsaw is the biggest city we expect the function to return us empty string "" but we got: " << NextCity;
-    
+    std::string NextCity =
```
Comment (JaroslawWiosna) [inline tests/ClosestCity/ClosestCity.cpp:117]: lowerCase, please

**Review by JaroslawWiosna — APPROVED** [review]
Good job. Approving, but take care of my comments, please

File: ClosestCity/ClosestCity.cpp (hunk 1 above)
Comment (kermit10000000) [reply ClosestCity/ClosestCity.cpp]: Ok, I will handle it with next commit

File: tests/ClosestCity/ClosestCity.cpp (hunk 3 above)
Comment (kermit10000000) [reply tests/ClosestCity/ClosestCity.cpp]: No you are right, I should use auto. There is no reason for keeping explicit definition.

File: tests/ClosestCity/ClosestCity.cpp (hunk 4 above)
Comment (kermit10000000) [reply tests/ClosestCity/ClosestCity.cpp:117]: Well, it looks better like this in my opinion unless there is some overall clean code rule. Therefore I will leave it now and ask you for why you request this?

File: Region/Region.cpp (hunk 2 above)
Comment (kermit10000000) [reply Region/Region.cpp:240]: Thank you

File: tests/ClosestCity/ClosestCity.cpp (hunk 4 above)
Comment (JaroslawWiosna) [reply tests/ClosestCity/ClosestCity.cpp:117]: @kermit10000000 I thought variable names should be lowercase. It is general rule, isn't it?
But merge anyway, it could be changed someday in the future.

Comment (kermit10000000) [reply tests/ClosestCity/ClosestCity.cpp:117]: Well, maybe yeah. I do not remember honestly There is no problem for me of course to go for it but I believe that rule should be stated somewhere if we want each contributor to follow it.
